trigger:
  branches:
    include:
      - dev
      - qa


stages:
  - stage: BuildAndDeployDev
    displayName: Build and Deploy Dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    jobs:
      - template: /azure-pipelines/azure-pipelines-dev.yml

  - stage: BuildAndDeployQA
    displayName: Build and Deploy QA
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/qa'))
    jobs:
      - template: /azure-pipelines/azure-pipelines-qa.yml

  